In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('diamonds_cleaned.csv',encoding='utf-8')

In [2]:
#Volume = x * y * z



df['volume'] = df['x'] * df['y'] * df['z']

In [3]:
#Price per Carat = price / carat
df['price_per_carat_usd'] = df['price'] / df['carat']

In [4]:
#Dimension Ratio = (x + y) / (2 * z)


df['dimension_ratio'] = (df['x'] + df['y']) / (2 * df['z'])

In [5]:
#Carat Category: Light (<0.5), Medium (0.5-1.5), Heavy (>1.5)

def carat_category(c):

    if c < 0.5:
        return 'Light'
    elif c <= 1.5:
        return 'Medium'
    else:
        return 'Heavy'
df['carat_category'] = df['carat'].apply(carat_category)

In [6]:
#Carat Category: Light (<0.5), Medium (0.5-1.5), Heavy (>1.5)

df[['carat','volume','price_per_carat_usd','carat_category']].head()

   carat     volume  price_per_carat_usd carat_category
0   0.23  38.202030          1417.391304          Light
1   0.21  34.505856          1552.380952          Light
2   0.23  38.076885          1421.739130          Light
3   0.29  46.724580          1151.724138          Light
4   0.31  51.917250          1080.645161          Light

In [7]:
#usd to inr conversion

usd_to_inr = 87.75   
df['price_inr'] = df['price'] * usd_to_inr
df['price_per_carat_inr'] = df['price_inr'] / df['carat']
print(f'Applied conversion: 1 USD = {usd_to_inr} INR')

Applied conversion: 1 USD = 87.75 INR

In [8]:
df.to_csv('diamonds_full.csv', encoding='utf-8', index=False)
df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z,price_log,volume,price_per_carat_usd,dimension_ratio,carat_category,price_inr,price_per_carat_inr
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,5.789960,38.202030,1417.391304,1.631687,Light,28606.50,124376.086957
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,5.789960,34.505856,1552.380952,1.673160,Light,28606.50,136221.428571
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,5.793014,38.076885,1421.739130,1.757576,Light,28694.25,124757.608696
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,5.814131,46.724580,1151.724138,1.602662,Light,29308.50,101063.793103
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,5.817111,51.917250,1080.645161,1.580000,Light,29396.25,94826.612903